PNC Neonatal Danger Sign Implementation
Digital-Square-Tanzania/opensrp-client-chw pull request #31
Opened 2023-08-25 12:39 UTC by devcolonel

Close #12

2023-08-28 08:39 UTC, cozej4 requested changes

2023-08-28 08:39 UTC, cozej4 commented on opensrp-chw/src/nacp/assets/json.form-sw/pnc_danger_signs_baby.json
> +        "openmrs_entity_id": "114403AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
We are phasing out the use of openmrs uuids here, please add the same value as the key

2023-08-28 08:39 UTC, cozej4 commented on opensrp-chw/src/nacp/assets/json.form-sw/pnc_danger_signs_baby.json
> +            "openmrs_entity_id": "1065AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
We are phasing out the use of openmrs uuids here, please add the same value as the key

2023-08-28 08:39 UTC, cozej4 commented on opensrp-chw/src/nacp/assets/json.form-sw/pnc_danger_signs_baby.json
> +            "openmrs_entity_id": "1066AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
We are phasing out the use of openmrs uuids here, please add the same value as the key

2023-08-28 08:39 UTC, cozej4 commented on opensrp-chw/src/nacp/assets/json.form-sw/pnc_danger_signs_baby.json
> +        "openmrs_entity_id": "114403AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
We are phasing out the use of openmrs uuids here, please add the same value as the key

2023-08-28 08:39 UTC, cozej4 commented on opensrp-chw/src/nacp/assets/json.form-sw/pnc_danger_signs_baby.json
> +            "openmrs_entity_id": "1065AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
We are phasing out the use of openmrs uuids here, please add the same value as the key

2023-08-28 08:39 UTC, cozej4 commented on opensrp-chw/src/nacp/assets/json.form-sw/pnc_danger_signs_baby.json
> +            "openmrs_entity_id": "1066AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
We are phasing out the use of openmrs uuids here, please add the same value as the key

2023-08-28 08:39 UTC, cozej4 commented on opensrp-chw/src/nacp/assets/json.form/pnc_danger_signs_baby.json
> +        "openmrs_entity_id": "114403AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
We are phasing out the use of openmrs uuids here, please add the same value as the key

2023-08-28 08:39 UTC, cozej4 commented on opensrp-chw/src/nacp/assets/json.form/pnc_danger_signs_baby.json
> +            "openmrs_entity_id": "1065AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
We are phasing out the use of openmrs uuids here, please add the same value as the key

2023-08-28 08:39 UTC, cozej4 commented on opensrp-chw/src/nacp/assets/json.form/pnc_danger_signs_baby.json
> +            "openmrs_entity_id": "1066AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
We are phasing out the use of openmrs uuids here, please add the same value as the key

2023-08-28 08:39 UTC, cozej4 commented on opensrp-chw/src/nacp/assets/json.form/pnc_danger_signs_baby.json
> +            "openmrs_entity_id": "1065AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
We are phasing out the use of openmrs uuids here, please add the same value as the key

2023-08-28 08:39 UTC, cozej4 commented on opensrp-chw/src/nacp/assets/json.form/pnc_danger_signs_baby.json
> +        "openmrs_entity_id": "114403AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
We are phasing out the use of openmrs uuids here, please add the same value as the key

2023-08-28 08:39 UTC, cozej4 commented on opensrp-chw/src/nacp/assets/json.form/pnc_danger_signs_baby.json
> +            "openmrs_entity_id": "1066AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
We are phasing out the use of openmrs uuids here, please add the same value as the key

2023-09-21 06:42 UTC, gosso22 approved these changes

2023-09-26 05:57 UTC, gosso22 commented
@cozej4 - this one is ready for review

2023-10-05 09:44 UTC, cozej4 approved these changes

2023-10-06 13:51 UTC, merged