PNC Mother Danger Sign Implementation
Digital-Square-Tanzania/opensrp-client-chw pull request #34
Opened 2023-08-25 13:05 UTC by devcolonel

Close #8

2023-08-28 08:28 UTC, cozej4 requested changes

2023-08-28 08:28 UTC, cozej4 commented on opensrp-chw/src/nacp/assets/json.form-sw/pnc_danger_signs_mother.json
> +        "openmrs_entity_id": "114403AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
We are phasing out the use of openmrs uuid in keys, please update this to use the same value as the key. This also applies to all other keys using the openmrs uuids in this form

2023-09-22 11:52 UTC, issyzac requested changes

2023-09-22 11:52 UTC, issyzac commented on opensrp-chw/src/nacp/assets/rule/pnc_danger_signs_mother_relevance.yml
> +description: If Danger Sign Present Refer Her to the Health Facility
Rule description does not match the condition

2023-09-25 12:23 UTC, issyzac approved these changes
👍🏾 👍🏾

2023-09-27 08:22 UTC, gosso22 commented
@cozej4 - can you approve these changes?

2023-10-05 09:44 UTC, cozej4 approved these changes

2023-10-06 14:17 UTC, merged