Child Home Visit Essential newborn care breastfeeding Module
Digital-Square-Tanzania/opensrp-client-chw pull request #43
Opened 2023-09-15 07:40 UTC by devcolonel

Close #15

2023-09-22 11:19 UTC, issyzac submitted a review, later dismissed
LGTM

2023-09-26 13:00 UTC, gosso22 commented on opensrp-chw/src/nacp/assets/recurring_service_types.json
@devcolonel - Please check the frequency on the breastfeeding content as per data dictionary and update here. https://docs.google.com/spreadsheets/d/1dr8uhaF9KN09DzcQf6-l_VsC6jXCQ5ddj1cKnuymkto/edit#gid=179989320&range=51:51 - look on specifically on cell 56. I think the definitions you have on this file here are monthly.

2023-09-26 13:01 UTC, gosso22 requested changes
Please revise on the recurring service definitions.

2023-10-02 06:41 UTC, gosso22 submitted a review, later dismissed
LGTM!

2023-10-02 10:02 UTC, gosso22 approved these changes, later dismissed

2023-10-02 12:57 UTC, gosso22 commented on opensrp-chw/src/nacp/assets/rule/child_hv_breastfeeding_relevance.yml
> +description: Check if Child Growth Present to do Growth Monitoring
@devcolonel - the description here is misleading can you change to reflect this rule?

2023-10-02 12:58 UTC, gosso22 approved these changes

2023-10-02 12:59 UTC, merged