Refactored waja to add referral during visit
Digital-Square-Tanzania/opensrp-client-chw pull request #61
Opened 2024-06-13 16:28 UTC by nKataraia

2024-06-20 09:51 UTC, gosso22 commented on opensrp-chw/build.gradle
> +        exclude group: 'com.ibm.fhir', module: 'fhir-path'
@nKataraia - I think this has been fixed so we dont need to exclude fhir-path library and include the version below.

2024-06-20 09:54 UTC, gosso22 commented on opensrp-chw/build.gradle
> +    implementation('org.smartregister:opensrp-client-chw-referral:1.3.13-NACP-LOCAL-ALPHA-SNAPSHOT@aar') {
@nKataraia - did you make any changes to the referral library? If not probably just leave this to the version others are using locally.

2024-06-20 10:34 UTC, gosso22 commented on opensrp-chw/src/nacp/java/org/smartregister/chw/interactor/ChildHomeVisitInteractorFlv.java
> +            evaluateToddlerDanger();
@nKataraia - evaluating other action inside danger signs makes danger signs mandatory, for the cases where there is no danger signs screening then no modules show with this implementation. Can you check out this scenario?

2024-06-20 12:52 UTC, gosso22 commented on opensrp-chw/src/test/java/org/smartregister/chw/Futa.java
@nKataraia - maybe you should remove this

2024-06-20 12:53 UTC, gosso22 commented on opensrp-chw/src/nacp/java/org/smartregister/chw/util/BoolEvaluator.java
@nKataraia - are you using this?

2024-06-20 12:56 UTC, gosso22 requested changes
@nKataraia - I have left you a couple of comments for this PR, overall this is an awesome implementation. It is fun to review :). I think you might need to look into Child and PNC. For child the danger signs is made to be a condition for other modules, so for the case of children who dont have danger signs screening (for example children older than 12 months) the visit doesnt show any module. For PNC, if you select danger signs, then go back and select none. it still shows refer facility module. I think this should disappear and show other modules.

Thanks for working on this.

2024-07-01 09:41 UTC, gosso22 approved these changes

2024-07-03 08:08 UTC, issyzac approved these changes

2024-07-03 08:08 UTC, issyzac commented on opensrp-chw/src/nacp/java/org/smartregister/chw/interactor/AncHomeVisitInteractorFlv.java
> +        JSONObject referralProblem=FacilitySelectionActionHelper.copyReferralProblem(referralPayload,"danger_signs_present");
Why do we have this implementation inside the action helper?

2024-07-03 13:49 UTC, merged